# Customized for RL4CO
_target_: rl4co.utils.trainer.RL4COTrainer

default_root_dir: ${paths.output_dir}

gradient_clip_val: 1.0
accelerator: "auto"
precision: "16-mixed"

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False