_target_: rl4co.models.SymNCO

num_augment: 10
num_starts: 0 # by default we use only symmetric augmentations

metrics:
  train: ["loss", "loss_ss", "loss_ps", "loss_inv", "reward"]
  val: ["reward", "max_reward", "max_aug_reward"]
  test: ${model.metrics.val}
  log_on_step: True
