_target_: rl4co.envs.CVRPTWEnv
name: cvrptw

generator_params:
  num_loc: 20
  loc_distribution: uniform

data_dir: ${paths.root_dir}/data/cvrptw
val_file: cvrptw${env.generator_params.num_loc}_val_seed4321.npz
test_file: cvrptw${env.generator_params.num_loc}_test_seed1234.npz