_target_: rl4co.envs.FLPEnv
name: flp

generator_params:
  num_loc: 100
  min_loc: 0.0
  max_loc: 1.0
  loc_distribution: uniform
  to_choose: 10

# data_dir: ${paths.root_dir}/data/mcp
# val_file: mcp${env.generator_params.num_loc}_val_seed4321.npz
# test_file: mcp${env.generator_params.num_loc}_test_seed1234.npz
