_target_: rl4co.envs.PDPEnv
name: pdp

generator_params:
  num_loc: 20
  min_loc: 0
  max_loc: 1
  loc_distribution: uniform

data_dir: ${paths.root_dir}/data/pdp
val_file: pdp${env.generator_params.num_loc}_val_seed4321.npz
test_file: pdp${env.generator_params.num_loc}_test_seed1234.npz