_target_: rl4co.envs.FJSPEnv
name: fjsp

generator_params:
  num_jobs: 15
  num_machines: 10
  min_ops_per_job: 8
  max_ops_per_job: 12
  min_processing_time: 1
  max_processing_time: 20
  min_eligible_ma_per_op: 1

data_dir: ${paths.root_dir}/data/fjsp
